import { describe, it, expect } from 'vitest';
import { hashToken, resolveIdentity, isIdentityError, generateAgentToken, generateAgentSalt } from './agent-auth.js';
import type { AgentAuthStore } from './agent-auth.contracts.js';

function makeStore(bindings: AgentAuthStore['bindings']): AgentAuthStore {
  return { bindings };
}

describe('agent-auth', () => {
  describe('hashToken', () => {
    it('produces a consistent hex hash', () => {
      const token = 'test-token-1234';
      const hash1 = hashToken(token);
      const hash2 = hashToken(token);
      expect(hash1).toBe(hash2);
      expect(hash1).toMatch(/^[0-9a-f]{64}$/);
    });

    it('supports salted token hashes for stored auth bindings', () => {
      const token = 'test-token-1234';
      const salt = 'auth-store-salt';
      expect(hashToken(token, salt)).toMatch(/^[0-9a-f]{64}$/);
      expect(hashToken(token, salt)).not.toBe(hashToken(token));
      expect(hashToken(token, salt)).toBe(hashToken(token, salt));
    });
  });

  describe('generateAgentToken', () => {
    it('generates a 64-char hex string', () => {
      const token = generateAgentToken();
      expect(token).toMatch(/^[0-9a-f]{64}$/);
    });

    it('generates unique tokens', () => {
      const a = generateAgentToken();
      const b = generateAgentToken();
      expect(a).not.toBe(b);
    });

    it('generates salts separately from bearer tokens', () => {
      const salt = generateAgentSalt();
      expect(salt).toMatch(/^[0-9a-f]{32}$/);
      expect(salt).not.toBe(generateAgentToken());
    });
  });

  describe('resolveIdentity', () => {
    const financeToken = 'finance-secret-token';
    const financeHash = hashToken(financeToken);
    const ceoToken = 'ceo-secret-token';
    const ceoHash = hashToken(ceoToken);

    const store = makeStore([
      { subject: financeHash, agentId: 'finance-agent', tenantId: 'default', enabled: true },
      { subject: ceoHash, agentId: 'ceo-agent', tenantId: 'default', enabled: true },
    ]);

    const resolveRoles = (agentId: string) => {
      if (agentId === 'finance-agent') return ['finance_approver'];
      if (agentId === 'ceo-agent') return ['ceo'];
      return [];
    };

    const isEnabled = (agentId: string) => agentId !== 'disabled-agent';

    it('resolves valid finance token to finance identity', () => {
      const result = resolveIdentity(financeToken, undefined, store, resolveRoles, isEnabled);
      expect(isIdentityError(result)).toBe(false);
      if (!isIdentityError(result)) {
        expect(result.agentId).toBe('finance-agent');
        expect(result.roles).toEqual(['finance_approver']);
      }
    });

    it('allows matching body agentId', () => {
      const result = resolveIdentity(financeToken, 'finance-agent', store, resolveRoles, isEnabled);
      expect(isIdentityError(result)).toBe(false);
    });

    it('rejects spoofed body agentId', () => {
      const result = resolveIdentity(financeToken, 'ceo-agent', store, resolveRoles, isEnabled);
      expect(isIdentityError(result)).toBe(true);
      if (isIdentityError(result)) {
        expect(result.code).toBe('agent_mismatch');
      }
    });

    it('rejects missing token', () => {
      const result = resolveIdentity(undefined, undefined, store, resolveRoles, isEnabled);
      expect(isIdentityError(result)).toBe(true);
      if (isIdentityError(result)) {
        expect(result.code).toBe('no_token');
      }
    });

    it('rejects unknown token', () => {
      const result = resolveIdentity('unknown-token', undefined, store, resolveRoles, isEnabled);
      expect(isIdentityError(result)).toBe(true);
      if (isIdentityError(result)) {
        expect(result.code).toBe('unknown_token');
      }
    });

    it('rejects disabled token binding before trusting agent identity', () => {
      const disabledStore = makeStore([
        { subject: financeHash, agentId: 'finance-agent', tenantId: 'default', enabled: false },
      ]);
      const result = resolveIdentity(financeToken, undefined, disabledStore, resolveRoles, isEnabled);
      expect(isIdentityError(result)).toBe(true);
      if (isIdentityError(result)) {
        expect(result.code).toBe('disabled_binding');
      }
    });

    it('rejects disabled agent', () => {
      const disabledStore = makeStore([
        { subject: financeHash, agentId: 'disabled-agent', tenantId: 'default', enabled: true },
      ]);
      const result = resolveIdentity(financeToken, undefined, disabledStore, resolveRoles, () => false);
      expect(isIdentityError(result)).toBe(true);
      if (isIdentityError(result)) {
        expect(result.code).toBe('agent_disabled');
      }
    });

    it('resolves salted bindings generated by provision', () => {
      const token = 'salted-finance-secret';
      const salt = 'salt-1';
      const saltedStore = makeStore([
        { subject: hashToken(token, salt), salt, agentId: 'finance-agent', tenantId: 'default', enabled: true },
      ]);
      const result = resolveIdentity(token, undefined, saltedStore, resolveRoles, isEnabled);
      expect(isIdentityError(result)).toBe(false);
      if (!isIdentityError(result)) {
        expect(result.agentId).toBe('finance-agent');
      }
    });
  });
});
