import { existsSync, mkdirSync, writeFileSync, readFileSync, chmodSync } from 'fs';
import { dirname, resolve } from 'path';
import { parse as parseYaml } from 'yaml';
import { loadAgentRegistry } from './agent-registry.js';
import { loadAccessPolicy, getAuthorisedBrains, verifyMounts, type AccessViolation } from './access-policy-loader.js';
import { generateAgentSalt, generateAgentToken, hashToken } from './agent-auth.js';
import type { AccessPolicyConfig } from './access-policy.contracts.js';
import { ToolInventorySchema } from './tool-inventory.contracts.js';
import { detectAgentEnvironment } from '../onboarding/detect-agent-env.js';
import { globMatches } from '../policy/glob-matcher.js';
import { createLogger } from '../utils/logger.js';

const logger = createLogger('provision');

export interface ProvisionResult {
  agentCount: number;
  tokensGenerated: number;
  envFilesWritten: string[];
  authBindingsWritten: string;
  warnings: string[];
}

export interface VerifyResult {
  ok: boolean;
  violations: AccessViolation[];
  warnings: string[];
  unknownTools: string[];
}

export function resolveProvisionAuthStorePath(outputDir: string): string {
  return resolve(outputDir, '..', 'agent-auth.yaml');
}

export async function provisionAgents(
  agentRegistryPath: string,
  accessPolicyPath: string,
  outputDir: string,
): Promise<ProvisionResult> {
  const registry = loadAgentRegistry(agentRegistryPath);
  const policy = loadAccessPolicy(accessPolicyPath);

  const resolvedOutputDir = resolve(outputDir);
  mkdirSync(resolvedOutputDir, { recursive: true });

  const envFiles: string[] = [];
  const warnings: string[] = [];
  const authBindings: Array<{ subject: string; salt: string; agentId: string; tenantId: string; enabled: boolean }> = [];

  for (const agent of registry.agents) {
    if (!agent.enabled) continue;

    const agentDir = resolve(resolvedOutputDir, agent.agentId);
    mkdirSync(agentDir, { recursive: true });

    const token = generateAgentToken();
    const salt = generateAgentSalt();
    const tokenHash = hashToken(token, salt);

    authBindings.push({
      subject: tokenHash,
      salt,
      agentId: agent.agentId,
      tenantId: registry.tenantId,
      enabled: true,
    });

    const authorisedBrains = getAuthorisedBrainsForAgent(policy, agent.roles);
    const mountList = authorisedBrains.join(',');

    const envContent = [
      `# ${agent.displayName} — generated by decision-core provision`,
      `DC_AGENT_ID=${agent.agentId}`,
      `DC_BASE_URL=http://127.0.0.1:3100`,
      `DC_API_KEY=${token}`,
      agent.personalBrain ? `GBRAIN_BRAIN_ID=${agent.personalBrain}` : '',
      `GBRAIN_MOUNTS=${mountList}`,
      '',
      `# Brains NOT mounted (access policy denies):`,
      ...getExcludedBrains(policy, agent.roles).map((b) => `# ${b.brain}: ${b.reason}`),
      '',
    ].filter(Boolean).join('\n');

    const envPath = resolve(agentDir, 'agent.env');
    writeFileSync(envPath, envContent, 'utf-8');
    try {
      chmodSync(envPath, 0o600);
    } catch {
      warnings.push(`Could not set permissions on ${envPath}`);
    }
    envFiles.push(envPath);

    const mountsJson = {
      agentId: agent.agentId,
      personalBrain: agent.personalBrain,
      sharedBrains: authorisedBrains,
    };
    writeFileSync(resolve(agentDir, 'mounts.json'), JSON.stringify(mountsJson, null, 2), 'utf-8');

    logger.info({ agentId: agent.agentId, brains: authorisedBrains.length }, 'Agent provisioned');
  }

  const authStorePath = resolveProvisionAuthStorePath(resolvedOutputDir);
  const authStoreContent = `bindings:\n${authBindings.map((b) =>
    `  - subject: "${b.subject}"\n    salt: "${b.salt}"\n    agentId: "${b.agentId}"\n    tenantId: "${b.tenantId}"\n    enabled: ${b.enabled}`,
  ).join('\n')}\n`;
  writeFileSync(authStorePath, authStoreContent, 'utf-8');
  try {
    chmodSync(authStorePath, 0o600);
  } catch {
    warnings.push(`Could not set permissions on ${authStorePath}`);
  }

  return {
    agentCount: registry.agents.filter((a) => a.enabled).length,
    tokensGenerated: authBindings.length,
    envFilesWritten: envFiles,
    authBindingsWritten: authStorePath,
    warnings,
  };
}

export async function verifyProvision(
  agentRegistryPath: string,
  accessPolicyPath: string,
  outputDir: string,
  policyPackPath?: string,
): Promise<VerifyResult> {
  const registry = loadAgentRegistry(agentRegistryPath);
  const policy = loadAccessPolicy(accessPolicyPath);
  const resolvedOutputDir = resolve(outputDir);

  const warnings: string[] = [];
  const unknownTools: string[] = [];

  const agentMounts: Array<{ agentId: string; roles: string[]; mountedBrains: string[] }> = [];

  for (const agent of registry.agents) {
    if (!agent.enabled) continue;

    const mountsPath = resolve(resolvedOutputDir, agent.agentId, 'mounts.json');
    if (!existsSync(mountsPath)) {
      warnings.push(`No mounts.json for ${agent.agentId} — run provision first`);
      continue;
    }

    const mounts = JSON.parse(readFileSync(mountsPath, 'utf-8'));
    const mountedBrains = (mounts.sharedBrains ?? []) as string[];

    agentMounts.push({
      agentId: agent.agentId,
      roles: agent.roles,
      mountedBrains,
    });
  }

  const violations = verifyMounts(policy, agentMounts);

  const authStorePath = resolveProvisionAuthStorePath(resolvedOutputDir);
  const legacyAuthStorePath = resolve(resolvedOutputDir, 'agent-auth.yaml');
  const effectiveAuthStorePath = existsSync(authStorePath) ? authStorePath : legacyAuthStorePath;
  if (!existsSync(effectiveAuthStorePath)) {
    warnings.push('No agent-auth.yaml found — token bindings missing');
  } else {
    const authStore = parseYaml(readFileSync(effectiveAuthStorePath, 'utf-8'));
    const bindings = (authStore?.bindings ?? []) as Array<{ agentId: string }>;
    for (const agent of registry.agents) {
      if (!agent.enabled) continue;
      if (!bindings.some((b) => b.agentId === agent.agentId)) {
        warnings.push(`No auth binding for enabled agent ${agent.agentId}`);
      }
    }
  }

  if (policyPackPath && existsSync(policyPackPath)) {
    const packContent = readFileSync(policyPackPath, 'utf-8');
    const parsedPack = parseYaml(packContent) as { denyUnknownDefault?: boolean; rules?: Array<{ actionTypePattern?: string }> } | null;
    const denyUnknown = parsedPack?.denyUnknownDefault === true;
    if (!denyUnknown) {
      warnings.push('Policy pack does not have denyUnknownDefault: true — unknown tools will be allowed');
    }

    const existingPatterns = (parsedPack?.rules ?? [])
      .map((rule) => rule.actionTypePattern)
      .filter((pattern): pattern is string => typeof pattern === 'string' && pattern.length > 0);
    const detectedTools = detectAgentEnvironment(process.cwd()).tools.map((tool) => tool.name);
    unknownTools.push(
      ...detectedTools.filter((toolName) =>
        !existingPatterns.some((pattern) => globMatches(pattern, toolName)),
      ),
    );

    const toolInventoryPath = resolve(dirname(resolve(policyPackPath)), 'tool-inventory.yaml');
    if (!existsSync(toolInventoryPath)) {
      warnings.push('No tool-inventory.yaml found — tool drift cannot be reviewed from a classified inventory');
    } else {
      const inventory = ToolInventorySchema.parse(parseYaml(readFileSync(toolInventoryPath, 'utf-8')));
      for (const tool of inventory.tools) {
        const hasPolicyRule = existingPatterns.some((pattern) =>
          globMatches(pattern, tool.name) || globMatches(tool.name, pattern),
        );
        if (!hasPolicyRule) {
          unknownTools.push(tool.name);
        }
      }
    }
  }

  return {
    ok: violations.length === 0 && warnings.length === 0,
    violations,
    warnings,
    unknownTools,
  };
}

function getAuthorisedBrainsForAgent(policy: AccessPolicyConfig, roles: string[]): string[] {
  const brains = new Set<string>();
  for (const role of roles) {
    for (const brain of getAuthorisedBrains(policy, role)) {
      if (!brain.includes('{')) {
        brains.add(brain);
      }
    }
  }
  return Array.from(brains);
}

function getExcludedBrains(
  policy: AccessPolicyConfig,
  roles: string[],
): Array<{ brain: string; reason: string }> {
  const authorised = new Set(getAuthorisedBrainsForAgent(policy, roles));
  const excluded: Array<{ brain: string; reason: string }> = [];

  for (const classification of policy.classifications) {
    if (classification.brain.includes('{')) continue;
    if (authorised.has(classification.brain)) continue;

    const neverRole = roles.find((r) => classification.neverAccessibleBy.includes(r));
    const reason = neverRole
      ? `${classification.name} classification (neverAccessibleBy: ${neverRole})`
      : `${classification.name} classification (not in accessibleBy)`;
    excluded.push({ brain: classification.brain, reason });
  }

  return excluded;
}
