/**
 * Structured Artifact Generator
 *
 * Takes a confirmed OnboardingProfile and generates the full .decision-core/
 * directory: profile, config, policies, surface contracts, tests, reports.
 */

import type { OnboardingProfile, ProfileTool } from '../contracts/onboarding-profile.contracts.js';
import { OnboardingProfileSchema } from '../contracts/onboarding-profile.contracts.js';
import { stringify as stringifyYaml } from 'yaml';

// ===========================================================================
// Output Types
// ===========================================================================

export interface GeneratedArtifact {
  path: string;
  content: string;
  category: 'profile' | 'config' | 'policy' | 'surface' | 'test' | 'integration' | 'report';
}

export interface GenerationResult {
  artifacts: GeneratedArtifact[];
  profileHash: string;
  generatedAt: string;
  warnings: string[];
}

// ===========================================================================
// Policy Generation
// ===========================================================================

function generateBaselinePolicy(profile: OnboardingProfile): string {
  const mode = profile.mode;
  const posture = profile.autonomy.posture;
  const action = toPolicyDecision(profile.autonomy.defaultAction);

  return `---
schema_version: "1.0.0"
policy_id: "baseline-${mode}"
title: "Baseline Policy — ${mode} mode"
description: "Auto-generated baseline policy for ${mode} setup"
effective_date: "${profile.createdAt}"
owner: "decision-core-setup"
surfaces:
  - workflow.escalation
---

# Baseline Policy

This policy was generated by Decision Core setup for **${mode}** mode with **${posture}** autonomy posture.

\`\`\`decision-core-clause
clause_id: baseline-default-action
clause_type: routing_constraint
surface_id: workflow.escalation
decision: "${action}"
safe_to_execute_without_model: true
rationale: "Default action for ${mode} mode with ${posture} posture"
\`\`\`

\`\`\`decision-core-clause
clause_id: baseline-unknown-action
clause_type: prohibition
surface_id: workflow.escalation
decision: "deny"
safe_to_execute_without_model: true
rationale: "Unknown actions are blocked by default"
\`\`\`
`;
}

function generateToolsPolicy(profile: OnboardingProfile): string {
  if (profile.tools.length === 0) return '';

  const clauses = profile.tools.map((tool) => {
    const surfaceId = surfaceForTool(tool);
    const action = decisionForTool(tool);
    const approvalRequired = tool.riskTier >= 3;
    const clauseType = tool.riskTier >= 4
      ? 'prohibition'
      : approvalRequired
        ? 'approval_requirement'
        : 'permission';

    return `\`\`\`decision-core-clause
clause_id: tool-${sanitizeId(tool.name)}
clause_type: ${clauseType}
surface_id: ${surfaceId}
decision: "${action}"
approval_required: ${approvalRequired}
safe_to_execute_without_model: true
rationale: "Risk tier ${tool.riskTier} tool${tool.canSpendMoney ? ' — can spend money' : ''}${tool.canDeleteData ? ' — can delete data' : ''}${tool.canDeployCode ? ' — can deploy code' : ''}"
\`\`\``;
  }).join('\n\n');

  const surfaces = [...new Set(profile.tools.map(surfaceForTool))];

  return `---
schema_version: "1.0.0"
policy_id: "tools-${profile.mode}"
title: "Tool Governance Policy"
description: "Auto-generated tool risk and approval rules"
effective_date: "${profile.createdAt}"
owner: "decision-core-setup"
surfaces:
${surfaces.map((s) => `  - ${s}`).join('\n')}
---

# Tool Governance

${clauses}
`;
}

function generateDataPolicy(profile: OnboardingProfile): string {
  if (profile.data.classes.length === 0) return '';

  const clauses = profile.data.classes.map((cls) => {
    const isSensitive = ['pii', 'financial', 'credentials', 'health', 'restricted'].includes(cls);

    return `\`\`\`decision-core-clause
clause_id: data-${cls}
clause_type: ${isSensitive ? 'obligation' : 'permission'}
surface_id: data.classification
decision: "${isSensitive ? 'approve_required' : 'allow'}"
safe_to_execute_without_model: true
rationale: "${cls} data classification${isSensitive ? ' — requires approval for access' : ''}"
\`\`\``;
  }).join('\n\n');

  return `---
schema_version: "1.0.0"
policy_id: "data-${profile.mode}"
title: "Data Handling Policy"
description: "Auto-generated data classification and handling rules"
effective_date: "${profile.createdAt}"
owner: "decision-core-setup"
surfaces:
  - data.classification
---

# Data Handling

${clauses}
`;
}

function generateProviderPolicy(profile: OnboardingProfile): string {
  return `---
schema_version: "1.0.0"
policy_id: "provider-routing"
title: "Provider Routing Policy"
description: "Auto-generated provider mode configuration"
effective_date: "${profile.createdAt}"
owner: "decision-core-setup"
surfaces:
  - workflow.routing
---

# Provider Routing

\`\`\`decision-core-clause
clause_id: provider-mode
clause_type: routing_constraint
surface_id: workflow.routing
decision: "allow"
safe_to_execute_without_model: true
rationale: "Provider mode set to ${profile.provider.mode} during setup"
\`\`\`
`;
}

function generateMemorySourcePolicy(profile: OnboardingProfile): string {
  const consented = profile.memory.sources.filter((s) => s.readConsent);
  if (consented.length === 0) return '';

  const clauses = consented.map((s) => {
    return `\`\`\`decision-core-clause
clause_id: memory-${sanitizeId(s.kind)}
clause_type: permission
surface_id: data.extraction
decision: "allow"
safe_to_execute_without_model: true
rationale: "Memory source ${s.kind} — read consent granted${s.writeBackConsent ? ', write-back consent granted' : ', read-only'}"
\`\`\``;
  }).join('\n\n');

  return `---
schema_version: "1.0.0"
policy_id: "memory-sources"
title: "Memory Source Policy"
description: "Documents consented memory sources for onboarding"
effective_date: "${profile.createdAt}"
owner: "decision-core-setup"
surfaces:
  - data.extraction
---

# Memory Sources

${clauses}
`;
}

// ===========================================================================
// Config Generation
// ===========================================================================

function generateProfileYaml(profile: OnboardingProfile): string {
  return `# Decision Core Profile
# Generated at: ${profile.createdAt}

schemaVersion: 1
profileId: "${profile.profileId}"
mode: "${profile.mode}"

agent:
  harness: "${profile.agent.harness}"
  detectedTools: ${JSON.stringify(profile.agent.detectedTools)}

autonomy:
  posture: "${profile.autonomy.posture}"
  defaultAction: "${profile.autonomy.defaultAction}"
  alwaysRequireApproval: ${JSON.stringify(profile.autonomy.alwaysRequireApproval)}

provider:
  mode: "${profile.provider.mode}"

memory:
  primarySource: ${profile.memory.primarySource ? `"${profile.memory.primarySource}"` : 'null'}
  evidenceImported: ${profile.memory.evidenceImported}
`;
}

function generateConfigYaml(profile: OnboardingProfile): string {
  return `# Decision Core Configuration
# Generated at: ${profile.createdAt}

version: 1
mode: "${profile.mode}"
provider:
  mode: "${profile.provider.mode}"
${profile.provider.envVarName ? `  envVarName: "${profile.provider.envVarName}"` : ''}
${profile.provider.localEndpoint ? `  localEndpoint: "${profile.provider.localEndpoint}"` : ''}
autonomy:
  posture: "${profile.autonomy.posture}"
  defaultAction: "${profile.autonomy.defaultAction}"
  enforcementMode: "${profile.autonomy.enforcementMode}"
`;
}

// ===========================================================================
// Surface Contract Generation
// ===========================================================================

function generateSurfaceContracts(profile: OnboardingProfile): string {
  if (profile.surfaces.length === 0 && profile.tools.length === 0) {
    return `# Surface Contracts
# No surfaces or tools configured
surfaces: []
`;
  }

  const toolsByRisk: Record<string, ProfileTool[]> = {};
  for (const tool of profile.tools) {
    const key = tool.riskTier >= 3 ? 'high_risk' : tool.riskTier >= 2 ? 'medium_risk' : 'standard';
    if (!toolsByRisk[key]) toolsByRisk[key] = [];
    toolsByRisk[key].push(tool);
  }

  const surfaces: Array<{ name: string; riskClass: 'A' | 'B' | 'C'; tools: string[] }> = [];

  if (toolsByRisk['high_risk']?.length) {
    surfaces.push({
      name: 'high-risk-operations',
      riskClass: 'A',
      tools: toolsByRisk['high_risk'].map((t) => t.name),
    });
  }

  if (toolsByRisk['medium_risk']?.length) {
    surfaces.push({
      name: 'standard-operations',
      riskClass: 'B',
      tools: toolsByRisk['medium_risk'].map((t) => t.name),
    });
  }

  if (toolsByRisk['standard']?.length) {
    surfaces.push({
      name: 'low-risk-operations',
      riskClass: 'C',
      tools: toolsByRisk['standard'].map((t) => t.name),
    });
  }

  return `# Surface Contracts\n# Generated at: ${profile.createdAt}\n\n${stringifyYaml({ surfaces })}`;
}

// ===========================================================================
// Report Generation
// ===========================================================================

function generateOnboardingReport(profile: OnboardingProfile, warnings: string[]): string {
  const detectedSources = profile.memory.sources.filter((s) => s.detected);
  const consentedSources = profile.memory.sources.filter((s) => s.readConsent);

  return `# Onboarding Report

**Profile:** ${profile.profileId}
**Mode:** ${profile.mode}
**Generated:** ${new Date().toISOString()}

## Agent

- **Harness:** ${profile.agent.harness}
- **Detected tools:** ${profile.agent.detectedTools.length}
- **Configured tools:** ${profile.tools.length}

## Autonomy

- **Posture:** ${profile.autonomy.posture}
- **Default action:** ${profile.autonomy.defaultAction}
- **Always require approval:** ${profile.autonomy.alwaysRequireApproval.join(', ') || 'none'}

## Provider

- **Mode:** ${profile.provider.mode}

## Memory Sources

- **Detected:** ${detectedSources.length}
- **Consented for read:** ${consentedSources.length}
- **Evidence imported:** ${profile.memory.evidenceImported}

## Data Classification

- **Classes:** ${profile.data.classes.join(', ') || 'none'}
- **Compliance frameworks:** ${profile.data.complianceFrameworks.join(', ') || 'none'}

## Evidence

- **Total evidence items:** ${profile.evidence.length}

${warnings.length > 0 ? `## Warnings\n\n${warnings.map((w) => `- ${w}`).join('\n')}\n` : ''}
`;
}

function generateMemorySourceReport(profile: OnboardingProfile): string {
  const rows = profile.memory.sources.map((source) =>
    `| ${source.kind} | ${source.detected ? 'yes' : 'no'} | ${source.readConsent ? 'yes' : 'no'} | ${source.writeBackConsent ? 'yes' : 'no'} | ${source.scope.join(', ') || 'none'} |`,
  );

  return `# Memory Source Report

**Profile:** ${profile.profileId}
**Generated:** ${new Date().toISOString()}

Memory sources are onboarding evidence inputs only. They are not policy truth.

| Source | Detected | Read consent | Write-back consent | Scope |
| --- | --- | --- | --- | --- |
${rows.length > 0 ? rows.join('\n') : '| none | no | no | no | none |'}
`;
}

function generateHarnessIntegration(profile: OnboardingProfile): GeneratedArtifact {
  if (profile.agent.harness === 'openclaw') {
    return {
      path: 'integrations/openclaw.yaml',
      category: 'integration',
      content: `# Decision Core OpenClaw integration
harness: openclaw
decisionCore:
  config: ../decision-core.config.yaml
  policies: ../policies
  policyPack: ../policy-pack.yaml
  mode: ${profile.mode}
  activation: active
provider:
  mode: ${profile.provider.mode}
memory:
  evidenceImported: ${profile.memory.evidenceImported}
`,
    };
  }

  if (profile.agent.harness === 'hermes') {
    return {
      path: 'integrations/hermes.yaml',
      category: 'integration',
      content: `# Decision Core Hermes integration
harness: hermes
decisionCore:
  config: ../decision-core.config.yaml
  policies: ../policies
  policyPack: ../policy-pack.yaml
  mode: ${profile.mode}
  activation: active
provider:
  mode: ${profile.provider.mode}
memory:
  evidenceImported: ${profile.memory.evidenceImported}
`,
    };
  }

  return {
    path: 'integrations/generic-hook.md',
    category: 'integration',
    content: `# Decision Core Generic Hook

Call Decision Core before tool execution:

\`\`\`ts
import { evaluate } from '@decision-core/core';

const decision = await evaluate({
  surface: 'workflow.routing',
  action: toolCall.name,
  context: toolCall.params,
});

if (decision.decision === 'deny') throw new Error('Blocked by Decision Core');
if (decision.decision === 'approve_required') await requestHumanApproval(decision);
\`\`\`

Store post-execution evidence only after successful execution and only within the consented scope.
`,
  };
}

// ===========================================================================
// Runtime Policy Pack Generation (SDK-format YAML)
// ===========================================================================

function generatePolicyPackYaml(profile: OnboardingProfile): string {
  const rules: Array<Record<string, unknown>> = [];

  for (const tool of profile.tools) {
    const verdict = runtimeVerdictForTool(tool);
    const actionType = sanitizeActionType(tool.name);
    const entry: Record<string, unknown> = {
      name: `tool-${sanitizeId(tool.name)}`,
      description: `Policy for ${tool.name} (risk tier ${tool.riskTier})`,
      actionTypePattern: actionType,
      riskClass: tool.riskTier >= 3 ? 'A' : tool.riskTier >= 2 ? 'B' : 'C',
      enforcementPoint: 'pre_decision',
      policyType: tool.riskTier >= 3 ? 'safety' : 'business',
      priority: 50 + tool.riskTier * 10,
      requireApproval: verdict === 'approve_required',
      enabled: true,
    };
    if (verdict === 'deny') {
      entry['defaultVerdict'] = 'deny';
    }
    rules.push(entry);
  }

  if (profile.mode === 'team' || profile.mode === 'business') {
    rules.push({
      name: 'team-destructive-approval',
      description: 'Team/business mode: destructive operations require approval',
      actionTypePattern: 'delete_*',
      riskClass: 'B',
      enforcementPoint: 'pre_decision',
      policyType: 'safety',
      priority: 80,
      requireApproval: true,
      enabled: true,
    });
  }

  if (profile.mode === 'enterprise') {
    rules.push({
      name: 'enterprise-destructive-deny',
      description: 'Enterprise mode: destructive operations denied',
      actionTypePattern: 'delete_*',
      riskClass: 'A',
      enforcementPoint: 'pre_decision',
      policyType: 'safety',
      priority: 90,
      requireApproval: false,
      defaultVerdict: 'deny',
      enabled: true,
    });
    rules.push({
      name: 'enterprise-admin-approval',
      description: 'Enterprise mode: admin operations require approval',
      actionTypePattern: 'admin_*',
      riskClass: 'A',
      enforcementPoint: 'pre_decision',
      policyType: 'compliance',
      priority: 85,
      requireApproval: true,
      enabled: true,
    });
  }

  if (profile.tools.length === 0) {
    rules.push({
      name: 'starter-allow-read',
      description: 'Starter rule allowing read operations',
      actionTypePattern: 'read_*',
      riskClass: 'C',
      enforcementPoint: 'pre_decision',
      policyType: 'business',
      priority: 10,
      requireApproval: false,
      enabled: true,
    });
  }

  return stringifyYaml({
    version: '1.0.0',
    name: `${profile.mode}-setup`,
    description: `Generated by decision-core setup for ${profile.mode} mode`,
    denyUnknownDefault: true,
    rules,
  });
}

function runtimeVerdictForTool(tool: ProfileTool): 'allow' | 'deny' | 'approve_required' {
  if (tool.riskTier >= 4) return 'deny';
  if (tool.riskTier >= 3) return 'approve_required';
  if (tool.defaultAction === 'block') return 'deny';
  if (tool.defaultAction === 'ask') return 'approve_required';
  return 'allow';
}

export function generateRootConfigYaml(profile: OnboardingProfile, policyPackRelPath: string): string {
  // The rules are REAL (denyUnknownDefault stays true); enforcementMode is what
  // makes a fresh install non-breaking. In 'observe' nothing is blocked — the
  // would-be denials are recorded so the operator can review before flipping to
  // 'enforce' (a one-line change here; no pack regeneration needed).
  return `# decision-core.yaml — root runtime config
# Generated by decision-core setup
# enforcementMode: 'observe' = non-blocking (records would-be denials). Switch to
# 'enforce' once you've reviewed the observed impact.

${stringifyYaml({
    tenantId: 'default',
    persistence: 'memory',
    tenantMode: 'single',
    policyPackPath: policyPackRelPath,
    denyUnknownDefault: true,
    enforcementMode: profile.autonomy.enforcementMode,
  })}`;
}

// ===========================================================================
// Test Scenario Generation
// ===========================================================================

function generateTestScenarios(profile: OnboardingProfile): string {
  const scenarios: Array<{ name: string; input: { action: string; surface?: string }; expected: string }> = [];

  scenarios.push({
    name: 'unknown action is denied',
    input: { action: 'unknown_tool', surface: 'api' },
    expected: 'deny',
  });

  for (const tool of profile.tools) {
    const expected = runtimeVerdictForTool(tool);
    scenarios.push({
      name: `tool ${tool.name} — risk tier ${tool.riskTier}`,
      input: { action: sanitizeActionType(tool.name), surface: 'api' },
      expected,
    });
  }

  return JSON.stringify(scenarios, null, 2);
}

// ===========================================================================
// Rollback Manifest
// ===========================================================================

function generateRollbackManifest(artifacts: GeneratedArtifact[], generatedAt: string): string {
  const files = [...artifacts.map((a) => a.path), 'rollback-manifest.json'];
  return JSON.stringify(
    {
      version: 1,
      generatedAt,
      files,
    },
    null,
    2,
  );
}

// ===========================================================================
// Helpers
// ===========================================================================

function sanitizeId(name: string): string {
  return name.replace(/[^a-zA-Z0-9_-]/g, '-').toLowerCase();
}

function sanitizeActionType(name: string): string {
  const sanitized = sanitizeId(name).replace(/-+/g, '-').replace(/^-|-$/g, '');
  return sanitized.length > 0 ? sanitized : 'tool';
}

function toPolicyDecision(action: string): string {
  if (action === 'allow') return 'allow';
  if (action === 'ask') return 'approve_required';
  return 'deny';
}

function decisionForTool(tool: ProfileTool): string {
  if (tool.riskTier >= 4) return 'deny';
  if (tool.riskTier >= 3) return 'approve_required';
  return toPolicyDecision(tool.defaultAction);
}

function surfaceForTool(tool: ProfileTool): string {
  if (tool.canSpendMoney) return 'finance.processing';
  if (tool.canContactPeople || tool.canPublishContent) return 'communication.email';
  if (tool.accessesSensitiveData) return 'data.classification';
  if (tool.canDeleteData || tool.canDeployCode || tool.riskTier >= 3) return 'workflow.escalation';
  if (tool.defaultAction === 'ask') return 'workflow.escalation';
  return 'workflow.routing';
}

function simpleHash(content: string): string {
  let hash = 0;
  for (let i = 0; i < content.length; i++) {
    const char = content.charCodeAt(i);
    hash = ((hash << 5) - hash + char) | 0;
  }
  return Math.abs(hash).toString(16).padStart(8, '0');
}

// ===========================================================================
// Main Generator
// ===========================================================================

export function generateArtifacts(profile: OnboardingProfile): GenerationResult {
  const validation = OnboardingProfileSchema.safeParse(profile);
  if (!validation.success) {
    return {
      artifacts: [],
      profileHash: '',
      generatedAt: new Date().toISOString(),
      warnings: [`Profile validation failed: ${validation.error.issues.map((i) => i.message).join(', ')}`],
    };
  }

  const warnings: string[] = [];
  const artifacts: GeneratedArtifact[] = [];

  artifacts.push({
    path: 'decision-core.profile.yaml',
    content: generateProfileYaml(profile),
    category: 'profile',
  });

  artifacts.push({
    path: 'decision-core.config.yaml',
    content: generateConfigYaml(profile),
    category: 'config',
  });

  artifacts.push({
    path: 'surface-contracts.yaml',
    content: generateSurfaceContracts(profile),
    category: 'surface',
  });

  const baseline = generateBaselinePolicy(profile);
  artifacts.push({ path: 'policies/000-baseline.md', content: baseline, category: 'policy' });

  const toolsPolicy = generateToolsPolicy(profile);
  if (toolsPolicy) {
    artifacts.push({ path: 'policies/010-tools.md', content: toolsPolicy, category: 'policy' });
  } else {
    warnings.push('No tools configured — skipping tool policy generation');
  }

  const dataPolicy = generateDataPolicy(profile);
  if (dataPolicy) {
    artifacts.push({ path: 'policies/020-data.md', content: dataPolicy, category: 'policy' });
  }

  artifacts.push({
    path: 'policies/030-provider-routing.md',
    content: generateProviderPolicy(profile),
    category: 'policy',
  });

  const memoryPolicy = generateMemorySourcePolicy(profile);
  if (memoryPolicy) {
    artifacts.push({ path: 'policies/040-memory-sources.md', content: memoryPolicy, category: 'policy' });
  }

  artifacts.push({
    path: 'policy-pack.yaml',
    content: generatePolicyPackYaml(profile),
    category: 'config',
  });

  artifacts.push({
    path: 'tests/generated-scenarios.json',
    content: generateTestScenarios(profile),
    category: 'test',
  });

  artifacts.push(generateHarnessIntegration(profile));

  const report = generateOnboardingReport(profile, warnings);
  artifacts.push({ path: 'reports/onboarding-report.md', content: report, category: 'report' });

  artifacts.push({
    path: 'memory-source-report.md',
    content: generateMemorySourceReport(profile),
    category: 'report',
  });

  artifacts.push({
    path: 'rollback-manifest.json',
    content: generateRollbackManifest(artifacts, profile.createdAt),
    category: 'config',
  });

  const profileHash = simpleHash(JSON.stringify(profile));

  return {
    artifacts,
    profileHash,
    generatedAt: new Date().toISOString(),
    warnings,
  };
}
